apiVersion: v1
kind: Pod
metadata:
  name: webhook2
  labels:
    app: webhook2
spec:
  containers:
    - name: ordersytem-webhook2
      image: viictorivo/ordersytem-webhook:1
      ports:
        - containerPort: 80
