apiVersion: v1
kind: Pod
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  containers:
    - name: ordersytem-webhook
      image: viictorivo/ordersytem-webhook:latest
      ports:
        - containerPort: 80
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: opaque-secret
              key: PASSWORD
