apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webhook-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70